### ISSUE TITLE
LV2 and VST3 builds don't load on Linux

### ISSUE THREAD

**Issue by prokoudine** [midilab/jc303#1]
From Ardour's log:

```
VST3 module-path '/home/alex/.vst3/JC303.vst3/Contents/x86_64-linux/JC303.so'
[Info]: Scanning: /home/alex/.vst3/JC303.vst3
[ERROR]: Could not load VST3 plugin '/home/alex/.vst3/JC303.vst3/Contents/x86_64-linux/JC303.so': /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found (required by /home/alex/.vst3/JC303.vst3/Contents/x86_64-linux/JC303.so)
Cannot load VST3 module: '/home/alex/.vst3/JC303.vst3/Contents/x86_64-linux/JC303.so'
Scan Failed.
```

I'm using Ubuntu 23.04.

**Comment by midilab** [comment]
Hi @prokoudine,

Thank you for reporting back.

Can you provide more contextual information please?

CPU model:
Ardour version:
Logs for failing LV2 too.

Does VST2 worked?

**Comment by prokoudine** [comment]
CPU model: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz

Ardour version: 7.5

Log for LV2: 

`lilv_lib_open(): error: Failed to open library /home/alex/.lv2/JC303.lv2/libJC303.so (/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found (required by /home/alex/.lv2/JC303.lv2/libJC303.so))`

Log for VST2:

```
[Info]: Scanning: /home/alex/.vst/libJC303.so
[ERROR]: Could not load VST2 plugin '/home/alex/.vst/libJC303.so': /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found (required by /home/alex/.vst/libJC303.so)
[WARNING]: Cannot open VST2 module '/home/alex/.vst/libJC303.so'
Scan Failed.
```

**Comment by midilab** [comment]
your glibc library is older than those required by JC303 plugin(GLIBC_2.38).

Can you please run the following command so we can know wich version you have right now on your system:
$ ldd --version

I will try to get a minimun requirements to make sure the compiled version works on most used linux distros out there.

So the solution will be to compile another release with an older glibc to make it compatible with distributions that uses older versions of glibc.

**Comment by prokoudine** [comment]
$ ldd --version
ldd (Ubuntu GLIBC 2.37-0ubuntu2) 2.37

**Comment by midilab** [comment]
Thank you,

I will release a new package with the plugins using a older GLIB, i will keep you posted here when its done, so you can download the new and compatible with your distro.

**Comment by midilab** [comment]
I've updated the latest release pack with a versions compatible with your distro and others most used around. also put a note on glibc versions required.

Can you please delete the old .zip file and download it again? same link: [jc303-linux64-plugins.zip](https://github.com/midilab/jc303/releases/download/v0.9/jc303-linux64-plugins.zip)

Please let me know!

**Comment by prokoudine** [comment]
Thanks, that works!
