### ISSUE TITLE
Build problem with current master version

### ISSUE THREAD

**Issue by ycollet** [midilab/jc303#12]
I tried  to build js303 on Fedora and I met the following error:
```
-- Configuring juceaide
-- Building juceaide
-- Exporting juceaide
[ 11%] Creating directories for 'juce-clap-extensions-populate'
[ 22%] Performing download step (git clone) for 'juce-clap-extensions-populate'
Clonage dans 'juce-clap-extensions-src'...
fatal : la référence n'est pas un arbre : 54d83e121545490fdbb2d3dec3ba0c1da6005dde
CMake Error at juce-clap-extensions-subbuild/juce-clap-extensions-populate-prefix/tmp/juce-clap-extensions-populate-gitclone.cmake:49 (message):
  Failed to checkout tag: '54d83e121545490fdbb2d3dec3ba0c1da6005dde'


gmake[2]: *** [CMakeFiles/juce-clap-extensions-populate.dir/build.make:102: juce-clap-extensions-populate-prefix/src/juce-clap-extensions-populate-stamp/juce-clap-extensions-populate-download] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/juce-clap-extensions-populate.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2

CMake Error at /usr/share/cmake/Modules/FetchContent.cmake:1662 (message):
  Build step for juce-clap-extensions failed: 2
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FetchContent.cmake:1802:EVAL:2 (__FetchContent_directPopulate)
  /usr/share/cmake/Modules/FetchContent.cmake:1802 (cmake_language)
  /usr/share/cmake/Modules/FetchContent.cmake:2016 (FetchContent_Populate)
  CMakeLists.txt:50 (FetchContent_MakeAvailable)


-- Configuring incomplete, errors occurred!
```

I replaced the commit ID 54d83e121545490fdbb2d3dec3ba0c1da6005dde in the CMakeLists.txt file with the last one of the repo https://github.com/free-audio/clap-juce-extensions and everything went fine

**Comment by midilab** [comment]
hi @ycollet,

Thanks for reporting back, will check and update asap.

Did you test the CLAP format with last one commit on clap-juce-extension, is it working normaly on this new version?

**Comment by ycollet** [comment]
Not yet. I still have a lot of work to do for the Audinux repository and the version for Fedora 40 / rawhide. But I see the light at the end of the tunnel :)
https://copr.fedorainfracloud.org/coprs/ycollet/audinux/
https://audinux.github.io/

**Comment by midilab** [comment]
Great work for audio linuxers around for the audinux!

I've just commit the GIT_TAG change to newest git commit: 0a3e7a6494788ea525e95e12a8b6a51640dcdc3e

Once again thank you for the contribution!
