### ISSUE TITLE
 [Feature request] openaudio integration

### ISSUE THREAD

**Issue by RustoMCSpit** [midilab/jc303#13]
It's an open-source plugin manager called StudioRack:
https://github.com/studiorack

The aim of the project is to provide a free open-source way to manage plugin dependencies and their versions. It would involve the following steps:

    Publish a Github release containing the plugin source along with metadata plugins.json
    Tag your Github repository with studiorack-plugin so it can be discovered
    Wait for the studiorack-registry to index your plugin (every 24 hours)
    Check the registry feed for your plugin to appear

**Comment by midilab** [comment]
Looks like a good way to spread an audio opensource project like jc303. Thanks for the reference @RustoMCSpit .

I will take a time to read everything about and try to publish it.

**Comment by RustoMCSpit** [comment]
> Looks like a good way to spread an audio opensource project like jc303. Thanks for the reference @RustoMCSpit .
> 
> I will take a time to read everything about and try to publish it.

join the discord if you help

**Comment by RustoMCSpit** [comment]
> Looks like a good way to spread an audio opensource project like jc303. Thanks for the reference @RustoMCSpit .
> 
> I will take a time to read everything about and try to publish it.

https://github.com/open-audio-stack/open-audio-stack-registry/pull/37

**Comment by RustoMCSpit** [comment]
i just did it for you, but youll have to maintain it every update

**Comment by RustoMCSpit** [comment]
added https://github.com/open-audio-stack/open-audio-stack-registry/pull/39

youll have to maintain it though for every update if you want it to be up to date

**Comment by RustoMCSpit** [comment]
added https://github.com/open-audio-stack/open-audio-stack-registry/pull/39

youll have to maintain it though for every update if you want it to be up to date
