### ISSUE TITLE
changeable screen size

### ISSUE THREAD

**Issue by RustoMCSpit** [midilab/jc303#15]

**Comment by midilab** [comment]
There is a on-going Pull Request where we are working on a new design wich is bigger than current one:
You can have an ideia how bigger will be based on the resources to be used.

https://github.com/midilab/jc303/pull/11/files#diff-e4cdf195233ecc6d057d423045d32414ec5a85f05401ef2c1e49b3f1105b6331

**Comment by RustoMCSpit** [comment]
well it would be good if the screen size was adjustable and not hardcoded

**Comment by RustoMCSpit** [comment]
> There is a on-going Pull Request where we are working on a new design wich is bigger than current one: You can have an ideia how bigger will be based on the resources to be used.
> 
> https://github.com/midilab/jc303/pull/11/files#diff-e4cdf195233ecc6d057d423045d32414ec5a85f05401ef2c1e49b3f1105b6331

where does that new gui allow for preset selection?

**Comment by midilab** [comment]
Presets are on Roadmap.

**Comment by midilab** [comment]
No plans also to do a changeable screen size. It is always open for anyone to pull request new features like that, i just dont think it worth the development time on this task.

**Comment by RustoMCSpit** [comment]
> No plans also to do a changeable screen size. It is always open for anyone to pull request new features like that, i just dont think it worth the development time on this task.

can this then be tagged NEEDS HELP and re-opened?
