### ISSUE TITLE
color palettes

### ISSUE THREAD

**Issue by RustoMCSpit** [midilab/jc303#16]
https://colorhunt.co/

using color palettes can make the gui look prettier than it is now

**Comment by midilab** [comment]
@amadeusp is the designer in charge, maybe you can reach him to talk about your ideas.

**Comment by RustoMCSpit** [comment]
> @amadeusp is the designer in charge, maybe you can reach him to talk about your ideas.

can they see the issues i made here?

**Comment by amadeusp** [comment]
@RustoMCSpit @midilab Is this in relation to my new design or the "old" one? And what exactly do you mean with using color palettes could make the GUI prettier? I mean, how would you apply colors to the GUI?

**Comment by RustoMCSpit** [comment]
> @RustoMCSpit @midilab Is this in relation to my new design or the "old" one? And what exactly do you mean with using color palettes could make the GUI prettier? I mean, how would you apply colors to the GUI?

hi! this is about the new design which is gray scale. i thought picking a color palette and applying it to the gui would look nicer. 

![image](https://github.com/midilab/jc303/assets/134429563/45aef2e5-d41b-4d13-9ec9-27700098a0d8)

> how would you apply colors to the GUI?

i would set up a system that would allow me to input hex color values to replace certain gui elements. that means there'd be (for example):
primary color hex:
secondary color hex:
text hex:
etc.

this would allow for quick developer testing and also would allow users to theme the gui with hex values they like themselves

**Comment by RustoMCSpit** [comment]
ive also made other issues in this repo about the gui @amadeusp

**Comment by amadeusp** [comment]
@RustoMCSpit Ah, I see. You know, I experimented with colors while working on the new design quite a bit and had a lot of fun with it too, but ultimately decided to go with a classic silver look for the first iteration of this new design.

Also, I am not sure how easy it would be to implement a partially hex values based UI as I think the current implementation is entirely pixel based.

However, I have designed everything with full SVG support in mind. So at least theoretically something like this could be implemented in the future, I guess.

@midilab What do you think?

**Comment by amadeusp** [comment]
> ive also made other issues in this repo about the gui @amadeusp

Could you perhaps provide the links? I will be happy to comment onto your suggestions.

**Comment by RustoMCSpit** [comment]
> > ive also made other issues in this repo about the gui @amadeusp
> 
> Could you perhaps provide the links? I will be happy to comment onto your suggestions.


https://github.com/midilab/jc303/issues

look at every issue, theyre all mine

**Comment by amadeusp** [comment]
> ive also made other issues in this repo about the gui @amadeusp

I have now looked at your other issues, but have no additional input on the individual topics. If you have specific questions for me, I will be happy to try and answer them.

**Comment by midilab** [comment]
> @midilab What do you think?

Anything programable color palete based can't be used on image based designs, wich is pretty much the standard for more advanced plugin GUIs nowdays and it is the choice for JC303 Gui. So no plans to change it. 

But we do have plans to make it theme-able, chose you skin at compile time(chose at runtime it will be a future feature), but each skin is a different pack of GUI resources and code to make it happen.

The same goes to resizeable screen. Working on GUI for plugins is a total different approach than working for WEB GUI for example. 

The only thing that worth a discusion here is about the color palete chosed for this new UI. @amadeusp is a very experienced designer with in depth knowledge about color science on that matter. 

So please, @RustoMCSpit elaborate your request so we can undesrtand what you mean. Is there a specific color pallete you think it migth be a better choice? and if there it is, please elaborate why it will be a better choice for us to pickup.

**Comment by RustoMCSpit** [comment]
> I have now looked at your other issues, but have no additional input on the individual topics. If you have specific questions for me, I will be happy to try and answer them.

well the only question i have is are you interested in implementing any of them

**Comment by RustoMCSpit** [comment]
> Anything programable color palete based can't be used on image based designs

can the images not be re-tinted with a filter over them?

> So please, @RustoMCSpit elaborate your request so we can undesrtand what you mean. Is there a specific color pallete you think it migth be a better choice?

im sure there is but it wouldnt be my right to choose, ive just provided the idea to look into it.

> please elaborate why it will be a better choice for us to pickup.

greyscale is soulless, having colors on a gui can also indicate what each thing does like how the surge xt dubstep theme colors each gui element based on if ir is 'audio' 'signal chain' 'envelops and filters' 'effects' etc

**Comment by amadeusp** [comment]
@RustoMCSpit If I see this correctly, only the ticket with the color palettes is still open.

You say “greyscale is soulless” and I understand what you mean when you add “colors on a gui can also indicate what each thing does”.

As I said, I decided against colors and silver at the time because I aimed for a kind of classic TB-303 look, if that makes any sense.

I can imagine that I could make colored variants of that same new design.

But since the JC-303 is a simple concept overall, I don't think colors necessarily make sense in terms of ergonomics (as it clearly does with Surge, for example).

But again, I'm not against colors, on the contrary, I actually love colorful designs. But then again, things like that are a question of effort too. Not just in terms of design, but also in terms of implementation.

However, my design, including the source data, will be openly available, so that modifications (not just made by me) should not be a problem in future.

Shall we wait for the implementation of the new design from a developer's point of view and then discuss further steps?

**Comment by RustoMCSpit** [comment]
> Shall we wait for the implementation of the new design from a developer's point of view and then eventually discuss further steps?

yes, but have the ability to use hex code colors to tint and the ability to change screen size in mind. screen size means try to use vector graphics

**Comment by RustoMCSpit** [comment]
> I aimed for a kind of classic TB-303 look


does that mean no visible waveforms, envelopes, etc.?

**Comment by RustoMCSpit** [comment]
sorry, it's not called surge xt. it's called andromena. you can see how different parts of the signal chain are colored
![image](https://github.com/midilab/jc303/assets/134429563/2525e977-0fef-43f2-a31d-4aacb52043e7)

**Comment by amadeusp** [comment]
> > Shall we wait for the implementation of the new design from a developer's point of view and then eventually discuss further steps?
> 
> yes, but have the ability to use hex code colors to tint and the ability to change screen size in mind. screen size means try to use vector graphics

Although I would love a vector based UI too, I don't think that this can be implemented with reasonable effort at the moment. Maybe in the near future. Cc @midilab

**Comment by amadeusp** [comment]
> > I aimed for a kind of classic TB-303 look
> 
> does that mean no visible waveforms, envelopes, etc.?

Since I'm not working on the development part of this project but only on the UI, I can't answer that. Personally, however, I think that it is obsolete, since at least the DAWs I know offer waveform visualization out of the box and such a function is therefore redundant (in my humble opinion).

**Comment by midilab** [comment]
@RustoMCSpit 
The project focus is only to make Open303 wide accessible thru different platforms and plugins format, anything else than that its not planned or desireble to be on ROADMAP. 

But the project is fully opensource via MIT license you can fork it and create a new version with more features as you wish.

But back to the issue, we are open source developers that do this work in spare time, no money reward, so time here is a prescious resource, and again, i dont think it worth the development time to make anything that is not on Roadmap(please check the README.md). 

Fancy features could be implemented in the future, but no guarantee...

**Comment by RustoMCSpit** [comment]
anything i suggest is just a recommendation, not a demand! i understand entirelyt :D 

feel free to tag this issue on your roadmap or add a roadmap tag to it

**Comment by RustoMCSpit** [comment]
> Anything programable color palette based can't be used on image based designs,

can the images not be re-tinted with a filter over them? theyre svgs?
