### ISSUE TITLE
No GUI on Windows

### ISSUE THREAD

**Issue by Loom-child** [midilab/jc303#5]
Hi,

I can't get the GUI to show up when loading version 0.9.1 win64 VST3 in the DAWS I use (Flstudio 20, Renoise 3 or Reaper 7).  The plugin loads fine but the plugin window is blank, except for a line of text : JC 303 - A Juce Port of Open 303 and the Juce logo that shows up for a few seconds. 

The plugin is functional otherwise and its parameters are accessible through the non GUI version of the plugin wrapper in hosts that offer such an option and are listed among the parameters that can be automated.

I'm running Windows 10 on a core i5 with 8Gb of ram and an onboard Intel HD.

Thanks !

J

**Comment by midilab** [comment]
Hi @Loom-child ,

Thanks for reporting, i will investigate it further asap and get back to you.

**Comment by midilab** [comment]
Found the root of the issue, my bad actualy, when releasing for all platforms i got into a development branch of jc303 inside windows machine, so i release wrongly the first release that has no GUI... 
Im prepering rigth now the next release with support for CLAP format too, soon on release area the new version with GUI to download.

**Comment by midilab** [comment]
So here it is the new released 0.9.2 with the correct repository branch and interface for windows:
https://github.com/midilab/jc303/releases/download/v0.9.2/jc303-0.9.2-win64-plugins.zip

thank you for reporting! please let me know!
