### ISSUE TITLE
macOS issue

### ISSUE THREAD

**Issue by ClarusAD** [midilab/jc303#6]
Audio Unit not working on macOS 10.14.6 (Mojave). LogicPro X 10.5.1 doesn't see it

**Comment by midilab** [comment]
> Known issues: MacOS AU not loading in M1 tested with ableton11, all other MacOS plugins format tested and working fine on M1!

Its a know bug reported on README.md. Apple asks any app under his platform to be signed, so you must have a apple developer account that charges you $100usd year for that. So i haven't signed any, maybe this could be related, but i cant tell. I suggest you try VST3 version or Clap.

**Comment by SomeoneCalledRob** [comment]
I'm not seeing it in Logic 10.6.3 on MacOS 10.15.7 (Intel). I've tried the usual de-quarantining command but it hasn't fixed it.

**Comment by midilab** [comment]
> I'm not seeing it in Logic 10.6.3 on MacOS 10.15.7 (Intel). I've tried the usual de-quarantining command but it hasn't fixed it.

Yes its a pain in the ass bug, i've try de-quarantine too, apple is constantly messing with developers that have the bad karma to maitain anything on that platform, its a mouse and cat run. 

Its not a so easy problem to solve, no mentions around juce and AU bugs around, i will need to carefully test different versions of Juce against different versions of Xcode maybe to find one that fits... 

But anyway,  this is a well know bug, its on TODO list to be solved when i got some time to dig futher on this, also if anyone would be avaliabe to test compile against different versions of xcode for AU load fix let me know!

**Comment by SomeoneCalledRob** [comment]
Both of us Logic users in this thread are running older versions of both MacOS and Logic. Perhaps it's not targeted at older systems, or perhaps not a univeral binary after all and therefore only able to run on m-series Macs? It's unusual for a plugin to not appear at all. Normally Logic's plugin manager likes to tell you exactly what issues it has with plugins it doesn't like.

**Comment by designerfuzzi** [comment]
suspicion: maintype and subtype must conform. In compiler flags i see subtype set but not maintype.. As far i know AU need both valid to even consider loading them.

**Comment by midilab** [comment]
> suspicion: au type and subtype must conform. In compiler flags i see subtype set but not maintype.. As far i know AU need both valid to even consider loading them. The Info.plist shows `<key>type</key><string></string>` so it is empty and `CFBundleSignature` as `????`. means `auval` will also ignore it very likely, it can not show up for validation therefore never appears in your DAW's list. Also versions and their strings differ sometime as `1` then again as `0.0.1`

thanks for the analisys, i will try asap to compile and test with your suggestions changes, make sure juce is generating the correct and expected format.

**Comment by designerfuzzi** [comment]
i think the type should/could be `aumu` 
according to this possible variants...
```objc
CF_ENUM(UInt32) {
	kAudioUnitType_Output				= 'auou',
	kAudioUnitType_MusicDevice			= 'aumu',
	kAudioUnitType_MusicEffect			= 'aumf',
	kAudioUnitType_FormatConverter			= 'aufc',
	kAudioUnitType_Effect				= 'aufx',
	kAudioUnitType_Mixer				= 'aumx',
	kAudioUnitType_Panner				= 'aupn',
	kAudioUnitType_Generator			= 'augn',
	kAudioUnitType_OfflineEffect			= 'auol',
	kAudioUnitType_MIDIProcessor			= 'aumi'
};
```

**Comment by midilab** [comment]
Glad to inform you all that we got it working!

Thanks for all the involved in this thread for testing and suggesting a fix. 

I had to change the AU_MAIN_TYPE from "kAudioUnitType_Generator kAudioUnitType_MusicDevice" to "kAudioUnitType_MusicDevice" only, based on @designerfuzzi suggestions.

Im just finishing exposing some internal parameters for sound MOD like devilfish and i will release a 0.10.1 probrably this weekend with new features and this AU apple fix.

**Comment by SomeoneCalledRob** [comment]
Great, thanks.

**Comment by midilab** [comment]
https://github.com/midilab/jc303/releases/tag/v0.10.1

let me know if it work so i can close the issue!

**Comment by SomeoneCalledRob** [comment]
It's now **working** on Logic 10.6 Intel.

**Comment by midilab** [comment]
glad to hear! 
wish you all a good acid time!
